name: CI
on: [ push, pull_request ]

jobs:
  package-rpm:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache Yum
      id: cache-yum
      uses: actions/cache@v1
      with:
        path: /var/cache/yum/
        key: ${{ runner.os }}-yum

    - name: Setup Building
      run: scripts/build-setup

    - name: Build RPM
      run: scripts/build

    - name: Create Github Artifact
      uses: actions/upload-artifact@v1
      with:
        name: k3s-selinux
        path: dist/rpm/noarch/
